package com.wirecard.ezlink.webservices.receipt;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;

import org.ksoap2.serialization.*;

import java.math.BigDecimal;

public class RecieptReq extends AttributeContainer implements KvmSerializable
{
    
    public String MERCHANTNO;
    
    public String ORDERNO;
    
    public String MERCHANTREFNO;
    
    public String CAN;
    
    public BigDecimal AMOUNT=BigDecimal.ZERO;
    
    public String RECIEPTDATA;

    public RecieptReq ()
    {
    }

    public RecieptReq(String mERCHANTNO, String oRDERNO, String mERCHANTREFNO,
			String cAN, BigDecimal aMOUNT, String rECIEPTDATA) {
		MERCHANTNO = mERCHANTNO;
		ORDERNO = oRDERNO;
		MERCHANTREFNO = mERCHANTREFNO;
		CAN = cAN;
		AMOUNT = aMOUNT;
		RECIEPTDATA = rECIEPTDATA;
	}

	public RecieptReq (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("MERCHANTNO"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MERCHANTNO");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MERCHANTNO = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.MERCHANTNO = (String)obj;
            }    
        }
        if (soapObject.hasProperty("ORDERNO"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ORDERNO");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ORDERNO = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ORDERNO = (String)obj;
            }    
        }
        if (soapObject.hasProperty("MERCHANTREFNO"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MERCHANTREFNO");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MERCHANTREFNO = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.MERCHANTREFNO = (String)obj;
            }    
        }
        if (soapObject.hasProperty("CAN"))
        {	
	        java.lang.Object obj = soapObject.getProperty("CAN");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.CAN = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.CAN = (String)obj;
            }    
        }
        if (soapObject.hasProperty("AMOUNT"))
        {	
	        java.lang.Object obj = soapObject.getProperty("AMOUNT");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.AMOUNT = new BigDecimal(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigDecimal){
                this.AMOUNT = (BigDecimal)obj;
            }    
        }
        if (soapObject.hasProperty("RECIEPTDATA"))
        {	
	        java.lang.Object obj = soapObject.getProperty("RECIEPTDATA");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.RECIEPTDATA = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.RECIEPTDATA = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return MERCHANTNO;
        }
        if(propertyIndex==1)
        {
            return ORDERNO;
        }
        if(propertyIndex==2)
        {
            return MERCHANTREFNO;
        }
        if(propertyIndex==3)
        {
            return CAN;
        }
        if(propertyIndex==4)
        {
            return this.AMOUNT!=null?this.AMOUNT.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return RECIEPTDATA;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MERCHANTNO";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ORDERNO";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MERCHANTREFNO";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CAN";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AMOUNT";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RECIEPTDATA";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
