package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class HTIEZLING_WS_REQ_BODY extends AttributeContainer implements KvmSerializable
{
    
    public HTIRecieptReq RecieptReq;
    
    public HTIRecieptReqError RecieptReqError;

    public HTIEZLING_WS_REQ_BODY ()
    {
    }

    public HTIEZLING_WS_REQ_BODY(HTIRecieptReq recieptReq,
			HTIRecieptReqError recieptReqError) {
		RecieptReq = recieptReq;
		RecieptReqError = recieptReqError;
	}

	public HTIEZLING_WS_REQ_BODY (java.lang.Object paramObj,HTIExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("RecieptReq"))
        {	
	        java.lang.Object j = soapObject.getProperty("RecieptReq");
	        this.RecieptReq = (HTIRecieptReq)__envelope.get(j,HTIRecieptReq.class);
        }
        if (soapObject.hasProperty("RecieptReqError"))
        {	
	        java.lang.Object j = soapObject.getProperty("RecieptReqError");
	        this.RecieptReqError = (HTIRecieptReqError)__envelope.get(j,HTIRecieptReqError.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return RecieptReq;
        }
        if(propertyIndex==1)
        {
            return RecieptReqError;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = HTIRecieptReq.class;
            info.name = "RecieptReq";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==1)
        {
            info.type = HTIRecieptReqError.class;
            info.name = "RecieptReqError";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
