package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;

import org.ksoap2.serialization.*;

public class HTIEZLING_WS_HEADER extends AttributeContainer implements KvmSerializable
{
    
    public HTIEnums.VERSION VERSION=HTIEnums.VERSION._1_x002E_0;
    
    public String SOURCETYPE;
    
    public String SOURCEID;
    
    public String DATETIME;
    
    public String IPADDRESS;
    
    public String SECURITYLEVEL;
    
    public String SIGNATURE;
    
    public String ENCRYPTIONCRYPTOGRAM;
    
    public String ACCESSCODE;
    
    public String STATUS;

    public HTIEZLING_WS_HEADER ()
    {
    }

    public HTIEZLING_WS_HEADER(
			com.wirecard.ezlink.webservices.tranxHistory.HTIEnums.VERSION vERSION,
			String sOURCETYPE, String sOURCEID, String dATETIME,
			String iPADDRESS, String sECURITYLEVEL, String sIGNATURE,
			String eNCRYPTIONCRYPTOGRAM, String aCCESSCODE, String sTATUS) {
		VERSION = vERSION;
		SOURCETYPE = sOURCETYPE;
		SOURCEID = sOURCEID;
		DATETIME = dATETIME;
		IPADDRESS = iPADDRESS;
		SECURITYLEVEL = sECURITYLEVEL;
		SIGNATURE = sIGNATURE;
		ENCRYPTIONCRYPTOGRAM = eNCRYPTIONCRYPTOGRAM;
		ACCESSCODE = aCCESSCODE;
		STATUS = sTATUS;
	}

	public HTIEZLING_WS_HEADER (java.lang.Object paramObj,HTIExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("VERSION"))
        {	
	        java.lang.Object obj = soapObject.getProperty("VERSION");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.VERSION = HTIEnums.VERSION.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof HTIEnums.VERSION){
                this.VERSION = (HTIEnums.VERSION)obj;
            }    
        }
        if (soapObject.hasProperty("SOURCETYPE"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SOURCETYPE");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SOURCETYPE = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SOURCETYPE = (String)obj;
            }    
        }
        if (soapObject.hasProperty("SOURCEID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SOURCEID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SOURCEID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SOURCEID = (String)obj;
            }    
        }
        if (soapObject.hasProperty("DATETIME"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DATETIME");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DATETIME = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.DATETIME = (String)obj;
            }    
        }
        if (soapObject.hasProperty("IPADDRESS"))
        {	
	        java.lang.Object obj = soapObject.getProperty("IPADDRESS");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.IPADDRESS = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.IPADDRESS = (String)obj;
            }    
        }
        if (soapObject.hasProperty("SECURITYLEVEL"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SECURITYLEVEL");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SECURITYLEVEL = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SECURITYLEVEL = (String)obj;
            }    
        }
        if (soapObject.hasProperty("SIGNATURE"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SIGNATURE");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SIGNATURE = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SIGNATURE = (String)obj;
            }    
        }
        if (soapObject.hasProperty("ENCRYPTIONCRYPTOGRAM"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ENCRYPTIONCRYPTOGRAM");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ENCRYPTIONCRYPTOGRAM = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ENCRYPTIONCRYPTOGRAM = (String)obj;
            }    
        }
        if (soapObject.hasProperty("ACCESSCODE"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ACCESSCODE");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ACCESSCODE = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ACCESSCODE = (String)obj;
            }    
        }
        if (soapObject.hasProperty("STATUS"))
        {	
	        java.lang.Object obj = soapObject.getProperty("STATUS");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.STATUS = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.STATUS = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.VERSION!=null?this.VERSION.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return SOURCETYPE;
        }
        if(propertyIndex==2)
        {
            return SOURCEID;
        }
        if(propertyIndex==3)
        {
            return DATETIME;
        }
        if(propertyIndex==4)
        {
            return IPADDRESS;
        }
        if(propertyIndex==5)
        {
            return SECURITYLEVEL;
        }
        if(propertyIndex==6)
        {
            return SIGNATURE;
        }
        if(propertyIndex==7)
        {
            return ENCRYPTIONCRYPTOGRAM;
        }
        if(propertyIndex==8)
        {
            return ACCESSCODE;
        }
        if(propertyIndex==9)
        {
            return STATUS;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "VERSION";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOURCETYPE";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SOURCEID";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DATETIME";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IPADDRESS";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SECURITYLEVEL";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SIGNATURE";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ENCRYPTIONCRYPTOGRAM";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ACCESSCODE";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "STATUS";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/request";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
