package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class HTIEZLING_WS_RES_BODY extends AttributeContainer implements KvmSerializable
{
    
    public HTIRecieptRes RecieptRes;
    
    public HTIRecieptResError RecieptResError;

    public HTIEZLING_WS_RES_BODY ()
    {
    }

    public HTIEZLING_WS_RES_BODY (java.lang.Object paramObj,HTIExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("RecieptRes"))
        {	
	        java.lang.Object j = soapObject.getProperty("RecieptRes");
	        this.RecieptRes = (HTIRecieptRes)__envelope.get(j,HTIRecieptRes.class);
        }
        if (soapObject.hasProperty("RecieptResError"))
        {	
	        java.lang.Object j = soapObject.getProperty("RecieptResError");
	        this.RecieptResError = (HTIRecieptResError)__envelope.get(j,HTIRecieptResError.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return RecieptRes;
        }
        if(propertyIndex==1)
        {
            return RecieptResError;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = HTIRecieptRes.class;
            info.name = "RecieptRes";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/response";
        }
        if(propertyIndex==1)
        {
            info.type = HTIRecieptResError.class;
            info.name = "RecieptResError";
            info.namespace= "http://ezlinkwebservices.com/service/Reciept/response";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
