package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------



public interface HTIIServiceEvents
{
    public void Starting();
    public void Completed(HTIOperationResult result);
}
