package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class VDGEZLING_WS__TRANX_RES_BODY extends AttributeContainer implements KvmSerializable
{
    
    public VDGTranxList TranxList=new VDGTranxList();
    
    public VDGTranxHistoryResError TranxHistoryResError;

    public VDGEZLING_WS__TRANX_RES_BODY ()
    {
    }

    public VDGEZLING_WS__TRANX_RES_BODY (java.lang.Object paramObj,VDGExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("TranxList"))
        {	
	        java.lang.Object j = soapObject.getProperty("TranxList");
	        this.TranxList = new VDGTranxList(j,__envelope);
        }
        if (soapObject.hasProperty("TranxHistoryResError"))
        {	
	        java.lang.Object j = soapObject.getProperty("TranxHistoryResError");
	        this.TranxHistoryResError = (VDGTranxHistoryResError)__envelope.get(j,VDGTranxHistoryResError.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return TranxList;
        }
        if(propertyIndex==1)
        {
            return TranxHistoryResError;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TranxList";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/response";
        }
        if(propertyIndex==1)
        {
            info.type = VDGTranxHistoryResError.class;
            info.name = "TranxHistoryResError";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/response";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
