package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------





public class VDGEnums
{

    public enum VERSION
    {
        
        _1_x002E_0(0,"1.0");
        
        private int code;
        private java.lang.String xmlValue;
        
        VERSION(int code ,java.lang.String xmlValue){
            this.code = code;
            this.xmlValue=xmlValue;
        }
    
        public int getCode(){
		    return code;
	    }
    
        @Override
        public String toString() {
            return xmlValue;
        }

        public static VERSION fromString(String str)
        {
            if (str.equals("1.0"))
                return _1_x002E_0;
		    return null;
        }
    }

    public enum VERSION_1
    {
        
        _1_x002E_0(0,"1.0");
        
        private int code;
        private java.lang.String xmlValue;
        
        VERSION_1(int code ,java.lang.String xmlValue){
            this.code = code;
            this.xmlValue=xmlValue;
        }
    
        public int getCode(){
		    return code;
	    }
    
        @Override
        public String toString() {
            return xmlValue;
        }

        public static VERSION_1 fromString(String str)
        {
            if (str.equals("1.0"))
                return _1_x002E_0;
		    return null;
        }
    }

}