package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------



public class VDGOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
