package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class VDGTranxHistoryDetail extends AttributeContainer implements KvmSerializable
{
    
    public String TRANXDATE;
    
    public String MERCHANTNAME;
    
    public BigDecimal AMOUNT=BigDecimal.ZERO;
    
    public String STATUS;

    public VDGTranxHistoryDetail ()
    {
    }

    public VDGTranxHistoryDetail (java.lang.Object paramObj,VDGExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("TRANXDATE"))
        {	
	        java.lang.Object obj = soapObject.getProperty("TRANXDATE");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.TRANXDATE = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.TRANXDATE = (String)obj;
            }    
        }
        if (soapObject.hasProperty("MERCHANTNAME"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MERCHANTNAME");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MERCHANTNAME = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.MERCHANTNAME = (String)obj;
            }    
        }
        if (soapObject.hasProperty("AMOUNT"))
        {	
	        java.lang.Object obj = soapObject.getProperty("AMOUNT");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.AMOUNT = new BigDecimal(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigDecimal){
                this.AMOUNT = (BigDecimal)obj;
            }    
        }
        if (soapObject.hasProperty("STATUS"))
        {	
	        java.lang.Object obj = soapObject.getProperty("STATUS");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.STATUS = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.STATUS = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return TRANXDATE;
        }
        if(propertyIndex==1)
        {
            return MERCHANTNAME;
        }
        if(propertyIndex==2)
        {
            return this.AMOUNT!=null?this.AMOUNT.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return STATUS;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "TRANXDATE";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/response";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MERCHANTNAME";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/response";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AMOUNT";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/response";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "STATUS";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/response";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
