package com.wirecard.ezlink.webservices.tranxHistory;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;

import org.ksoap2.serialization.*;

import java.math.BigInteger;

public class VDGTranxHistoryReq extends AttributeContainer implements KvmSerializable
{
    
    public String CARDNO;
    
    public BigInteger REQUIREDNOOFREC=BigInteger.ZERO;

    public VDGTranxHistoryReq ()
    {
    }

    public VDGTranxHistoryReq(String cARDNO, BigInteger rEQUIREDNOOFREC) {
		CARDNO = cARDNO;
		REQUIREDNOOFREC = rEQUIREDNOOFREC;
	}

	public VDGTranxHistoryReq (java.lang.Object paramObj,VDGExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("CARDNO"))
        {	
	        java.lang.Object obj = soapObject.getProperty("CARDNO");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.CARDNO = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.CARDNO = (String)obj;
            }    
        }
        if (soapObject.hasProperty("REQUIREDNOOFREC"))
        {	
	        java.lang.Object obj = soapObject.getProperty("REQUIREDNOOFREC");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.REQUIREDNOOFREC = new BigInteger(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigInteger){
                this.REQUIREDNOOFREC = (BigInteger)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return CARDNO;
        }
        if(propertyIndex==1)
        {
            return this.REQUIREDNOOFREC!=null?this.REQUIREDNOOFREC.toString():SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CARDNO";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/request";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "REQUIREDNOOFREC";
            info.namespace= "http://ezlinkwebservices.com/service/TranxHistory/request";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
