package com.wirecard.ezlink.webservices.debitCommand;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DebitCommandResError extends AttributeContainer implements KvmSerializable
{
    
    public String DCERRORCODE;
    
    public String DCERRORDESC;

    public DebitCommandResError ()
    {
    }

    public DebitCommandResError (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("DCERRORCODE"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DCERRORCODE");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DCERRORCODE = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.DCERRORCODE = (String)obj;
            }    
        }
        if (soapObject.hasProperty("DCERRORDESC"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DCERRORDESC");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DCERRORDESC = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.DCERRORDESC = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DCERRORCODE;
        }
        if(propertyIndex==1)
        {
            return DCERRORDESC;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DCERRORCODE";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DCERRORDESC";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
