package com.wirecard.ezlink.webservices.debitCommand;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DebitCommandRes extends AttributeContainer implements KvmSerializable
{
    
    public String ORDERNO;
    
    public String MERCHANTREFNO;
    
    public String CAN;
    
    public String DEBITCOMMAND;

    public DebitCommandRes ()
    {
    }

    public DebitCommandRes (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ORDERNO"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ORDERNO");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ORDERNO = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ORDERNO = (String)obj;
            }    
        }
        if (soapObject.hasProperty("MERCHANTREFNO"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MERCHANTREFNO");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MERCHANTREFNO = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.MERCHANTREFNO = (String)obj;
            }    
        }
        if (soapObject.hasProperty("CAN"))
        {	
	        java.lang.Object obj = soapObject.getProperty("CAN");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.CAN = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.CAN = (String)obj;
            }    
        }
        if (soapObject.hasProperty("DEBITCOMMAND"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DEBITCOMMAND");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DEBITCOMMAND = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.DEBITCOMMAND = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return ORDERNO;
        }
        if(propertyIndex==1)
        {
            return MERCHANTREFNO;
        }
        if(propertyIndex==2)
        {
            return CAN;
        }
        if(propertyIndex==3)
        {
            return DEBITCOMMAND;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ORDERNO";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MERCHANTREFNO";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CAN";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DEBITCOMMAND";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
