package com.wirecard.ezlink.webservices.debitCommand;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class EZLING_WS_REQ_BODY extends AttributeContainer implements KvmSerializable
{
    
    public DebitCommandReq DebitCommandReq;

    public EZLING_WS_REQ_BODY ()
    {
    }

    public EZLING_WS_REQ_BODY(
			com.wirecard.ezlink.webservices.debitCommand.DebitCommandReq debitCommandReq) {
		DebitCommandReq = debitCommandReq;
	}

	public EZLING_WS_REQ_BODY (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("DebitCommandReq"))
        {	
	        java.lang.Object j = soapObject.getProperty("DebitCommandReq");
	        this.DebitCommandReq = (DebitCommandReq)__envelope.get(j,DebitCommandReq.class);
        }


    }

	@Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DebitCommandReq;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = DebitCommandReq.class;
            info.name = "DebitCommandReq";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/request";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
