package com.wirecard.ezlink.webservices.debitCommand;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 30-03-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class EZLING_WS_RES_BODY extends AttributeContainer implements KvmSerializable
{
    
    public DebitCommandRes DebitCommandRes;
    
    public DebitCommandResError DebitCommandResError;

    public EZLING_WS_RES_BODY ()
    {
    }

    public EZLING_WS_RES_BODY (java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("DebitCommandRes"))
        {	
	        java.lang.Object j = soapObject.getProperty("DebitCommandRes");
	        this.DebitCommandRes = (DebitCommandRes)__envelope.get(j,DebitCommandRes.class);
        }
        if (soapObject.hasProperty("DebitCommandResError"))
        {	
	        java.lang.Object j = soapObject.getProperty("DebitCommandResError");
	        this.DebitCommandResError = (DebitCommandResError)__envelope.get(j,DebitCommandResError.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return DebitCommandRes;
        }
        if(propertyIndex==1)
        {
            return DebitCommandResError;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = DebitCommandRes.class;
            info.name = "DebitCommandRes";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
        if(propertyIndex==1)
        {
            info.type = DebitCommandResError.class;
            info.name = "DebitCommandResError";
            info.namespace= "http://ezlinkwebservices.com/service/DebitCommand/response";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
